/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Slava Z. (https://sketchfab.com/slava)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
title: Pony Cartoon
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";

import url from "../assets/pony_cartoon/scene.gltf";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useLoader(
    GLTFLoader,
    url,
    draco("/draco-gltf/")
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0, 0, 0]}>
          <mesh
            material={materials.Body_SG1}
            geometry={nodes.mesh_0.geometry}
          />
          <mesh
            material={materials.Ground_SG}
            geometry={nodes.mesh_1.geometry}
          />
          <mesh
            material={materials.Interior_SG}
            geometry={nodes.mesh_2.geometry}
          />
          <mesh
            material={materials.Windows_SG}
            geometry={nodes.mesh_3.geometry}
          />
        </group>
      </group>
    </group>
  );
}
