/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";
import { DoubleSide } from "three";

export default function Terrain(props) {
  const group = useRef();
  const mesh = useRef();
  const { nodes, materials, animations, textures } = useLoader(
    GLTFLoader,
    `${process.env.PUBLIC_URL}/olympia_terrain/olympia_terrain.glb`,
    draco("/draco-gltf/")
  );
  useEffect(() => {
    console.log(nodes);
    console.log(materials);
    console.log(textures);
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow={true}
        receiveShadow={true}
        ref={mesh}
        scale={[100, 100, 100]}
        material={materials.olympia_satellite_google_z19_epsg3857}
        geometry={nodes.olympia_satellite_google_z19_epsg3857.geometry}
        map={`${process.env.PUBLIC_URL}/olympia_terrain/textures/olympia_satellite_google_z19_epsg3857.tif`}
      />
    </group>
  );
}
